name: Code Quality

on: [pull_request]

jobs:
  golangci-lint:
    name: Lint Golang files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33
          only-new-issues: true
  super-lint:
    name: Lint non-Golang files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false
          VALIDATE_ALL_CODEBASE: false
