name: Code Quality

on: [pull_request]

jobs:
  golangci-lint:
    name: Lint Golang files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.33
          only-new-issues: false
  super-lint:
    name: Lint non-Golang files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v4.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: "."
          VALIDATE_GO: false
          VALIDATE_ALL_CODEBASE: false
