# This workflow integrates ShiftLeft Scan with GitHub's code scanning feature
# ShiftLeft Scan is a free open-source security tool for modern DevOps teams
# Visit https://docs.shiftleft.io/shiftleft/scan/integrations/github-actions for help
name: Security

on: [push, pull_request]

jobs:
  scan:
    name: ShiftLeft Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ShiftLeftSecurity/scan-action@master
        env:
          WORKSPACE: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true
          PR_COMMENT_TEMPLATE: "## Scan Summary\n%(summary)s\n## Recommendation\n%(recommendation)s\n"
        with:
          output: reports
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reports
      - name: Upload scan reports
        uses: actions/upload-artifact@v1.0.0
        with:
          name: shiftleft-scan-reports
          path: reports
  analyze:
    name: Github CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: go
      - uses: github/codeql-action/autobuild@v1
      - uses: github/codeql-action/analyze@v1
