# This workflow integrates ShiftLeft Scan with GitHub's code scanning feature
# ShiftLeft Scan is a free open-source security tool for modern DevOps teams
# Visit https://slscan.io/en/latest/ for help
name: Security

on:
  push:
    branches: [master]
  pull_request:

jobs:
  scan:
    name: ShiftLeft Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ShiftLeftSecurity/scan-action@master
        env:
          WORKSPACE: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true
          PR_COMMENT_TEMPLATE: "## Scan Summary\n%(summary)s\n## Recommendation\n%(recommendation)s\n"
        with:
          output: reports
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reports
      - name: Upload scan reports
        uses: actions/upload-artifact@v2.3.0
        with:
          name: shiftleft-scan-reports
          path: reports
  analyze:
    name: Github CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: go
      - uses: github/codeql-action/autobuild@v1
      - uses: github/codeql-action/analyze@v1
  gitleaks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
  trivy-repo:
    name: Trivy Repository Scan
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          exit-code: 0
