name: Testing

on:
  push:
    branches: [master]
  pull_request:

jobs:
  cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.14", "1.15"]
    name: Build Cache (go v${{ matrix.go }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-
      - run: go mod download
        if: steps.cache-deps.outputs.cache-hit != 'true'
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.14", "1.15"]
    name: Run Unit Tests (go v${{ matrix.go }})
    needs: cache
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('go.sum') }}
      - run: go install github.com/onsi/ginkgo/ginkgo
      - run: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress --compilers=2 --nodes=2
  integration-test:
    runs-on: ubuntu-latest
    name: Run Integration Tests (go v1.15)
    needs: cache
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.15-${{ hashFiles('go.sum') }}
      - run: go install github.com/onsi/ginkgo/ginkgo
      - run: ginkgo --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress --compilers=1 --nodes=1 -tags "integration" pkg/rest
        env:
          IEXCLOUD_TOKEN: ${{ secrets.IEXCLOUD_TOKEN }}
  tag:
    runs-on: ubuntu-latest
    needs: [unit-test]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          append_to_pre_release_tag: pre
          # ['major', 'premajor', 'minor', 'preminor', 'patch', 'prepatch', 'prerelease']
          custom_release_rules: FIX:patch,FEAT:minor,BREAK:major
